// Get all blogs
GET http://localhost:3003/api/blogs

###

// Send blog
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 123,
    "userId": "65b9bffc225fb22d1b61186d"
}


###

// Delete blog
DELETE http://localhost:3003/api/blogs/65ac46bb47e1ac53f98c822f

###

// Update likes
PUT http://localhost:3003/api/blogs/65af303422860b3ed7ccc3e0
content-type: application/json

{
    "title": "titleTest",
    "author": "authorTest",
    "url": "urlTest",
    "likes": 222
}