// Get all blogs
GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvIiwiaWQiOiI2NWMxN2E0MWIzNTY3MGM4OTkwZWExOWYiLCJpYXQiOjE3MDcxNzg1ODF9.MNchjQmmM4uXQtPN-Fwkj9HyR6qxQY8M5i-5MUAQOyQ

###

// Send blog
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvIiwiaWQiOiI2NWMxN2E0MWIzNTY3MGM4OTkwZWExOWYiLCJpYXQiOjE3MDcxNzg1ODF9.MNchjQmmM4uXQtPN-Fwkj9HyR6qxQY8M5i-5MUAQOyQ

{
    "title": "AAA",
    "author": "Unknown",
    "url": "https://",
    "likes": 123
}


###

// Delete blog
DELETE http://localhost:3003/api/blogs/65c17f10f049ec353de27eb6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdDIiLCJpZCI6IjY1YmQ5ZTk3NDQ4ZDMzYjYwYzNhZjgzMiIsImlhdCI6MTcwNzE3ODQ4OX0.4FQgiP9KzvNVhFPWDmydm-UYP37wfBV6hhxKiSCgMz0


###

// Update likes
PUT http://localhost:3003/api/blogs/65af303422860b3ed7ccc3e0
content-type: application/json

{
    "title": "titleTest",
    "author": "authorTest",
    "url": "urlTest",
    "likes": 222
}